spring:
  application:
    name: jchatmind
  datasource:
    url: jdbc:postgresql://localhost:5432/jchatmind
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.qq.com
    port: 587
    username: 2258149585@qq.com
    password: qwdjopisupkqeaaj # 邮箱授权码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  ai:
    deepseek:
      api-key: sk-a743ac86c6434773b61ff6cdd8b13793
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    zhipuai:
      api-key: e0b5d2f4b50649c5969763b8453e03f7.0Xr9DwaxusTAAVpl
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: glm-4.6
mybatis:
  type-aliases-package: com.kama.jchatmind.model.entity
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.kama.jchatmind.typehandler

rag:
  chunking:
    max-tokens: 512
    overlap-ratio: 0.15

document:
  storage:
    base-path: ./data/documents
